http://localhost:3003/api/blogs HTTP/1.1
###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "blii",
    "author": "bluu",
    "url": "blaa",
    "likes": "123"
}
###
http://localhost:3003/api/users HTTP/1.1
###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "root1",
    "name": "Superuser",
    "password": "salainen"
}
###
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "root1",
    "password": "salainen"
}